### ISSUE TITLE
Omnisharp connects but fails to work

### ISSUE THREAD

**Issue by Mallchad** [emacs-lsp/lsp-mode#1125]
**Describe the bug**
 After connecting the omnisharp language server when opening a `.cs file`, nothing much in it just for test purposes to see if the server worked I always get errors, either `System.NullReferenceException` or `(wrong-type-argument hash-table-p nil)` like mentioned in #815
I believe this is purely an lsp-mode problem because standalone omnisharp-emacs (https://github.com/OmniSharp/omnisharp-emacs) works just fine almost out of the box even though they use the same server of omnisharp-roslyn
Flycheck also states that "A suitable syntax checker is not found." despite the connecting to the language server.
**To Reproduce**
Emacs with lsp mode hooked onto prog-mode.
omnisharp roslyn release or build placed in `~/.omnisharp/omnisharp/omnisharp`
empty C# file, hovering over any text will give you the error

**Expected behavior**
I expected to get either some kind of flycheck error or C# related company popup while typing or manually invoking `M-x company-lsp`

**Which Language Server did you use**
Omnisharp-Roslyn, release, manual build using including build.ps1 and through copying over Omnisharp-emacs files
**OS**
Which os do you use?
WIndows 10
**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer and the content of the server log(use `lsp-workspace-show-log`)
**LSP Log Error**
```
Failed to handle notification textDocument/signatureHelp - System.NullReferenceException: Object reference not set to an instance of an object.

   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpSignatureHelpHandler.<Handle>d__3.MoveNext() in D:\a\1\s\src\OmniSharp.LanguageServerProtocol\Handlers\OmniSharpSignatureHelpHandler.cs:line 45

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__6.MoveNext()
Finished: Routing Request (6) textDocument/signatureHelp in 23ms
```
**LSP Full Log**
(https://gist.github.com/Mallchad/b6c7900b6975d5169826bae963bcf994)
**LSP IO Log Error**
```[Trace - 03:03:33 PM] Received notification 'window/logMessage'.
Params: {
  "message": "Failed to handle notification textDocument/signatureHelp - System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpSignatureHelpHandler.<Handle>d__3.MoveNext() in D:\\a\\1\\s\\src\\OmniSharp.LanguageServerProtocol\\Handlers\\OmniSharpSignatureHelpHandler.cs:line 45\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__6.MoveNext()",
  "type": 1
}
```
**LSP IO Full Log**
(https://gist.github.com/Mallchad/decd44f66df2cc973391aabb5a1201b9)

**Comment by yyoncho** [comment]
Are you sure that you are using the latest version of the omnisharp? There were a lot of issues fixed in omnisharp regarding lsp support.

**Comment by Mallchad** [comment]
@yyoncho both tried the one installed from Omnisharp and actual omnisharp-roslyn page but I'll try and see if I can find an unstable branch that works when I get a chance.

**Comment by ptdel** [comment]
I'm also getting this issue:
```Failed to handle notification textDocument/signatureHelp - System.NullReferenceException: Object reference not set to an instance of an object
  at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpSignatureHelpHandler.Handle (OmniSharp.Extensions.LanguageServer.Protocol.Models.SignatureHelpParams request, System.Threading.CancellationToken token) [0x000d1] in <4f606786ff8f4b28a835225ed6e367d1>:0 
  at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2[TRequest,TResponse].Handle (TRequest request, System.Threading.CancellationToken cancellationToken, OmniSharp.Extensions.Embedded.MediatR.RequestHandlerDelegate`1[TResponse] next) [0x000e1] in <12a97e97079c4b10a770c2869fa566a9>:0 
  at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1[TDescriptor].RouteRequest (TDescriptor descriptor, OmniSharp.Extensions.JsonRpc.Server.Request request, System.Threading.CancellationToken token) [0x0038a] in <709d80c63bce4fcd8b1071c79413b97b>:0 ```

followed by:
```
Error running timer: (wrong-type-argument hash-table-p nil) [4 times]
```

Omnisharp-Roslyn is on v1.34.7
Mono on 6.4.0
MSBuild 16.3

I can confirm that I don't get this issue with standalone Omnisharp-Emacs

**Comment by Mallchad** [comment]
I couldn't find a newer version of omnisharp-roslyn. but I tried older versions, namley a 6 month old one, linux vs windows, even gave it a go on msys. I tried an older lsp-mode.el . Couldn't get any of them working. I might have messed up trying an older version of omnisharp-roslyn, but I can only assume that there is something wrong with lsp-mode in my particular configuration.

**Comment by yyoncho** [comment]
@Mallchad can you try with the latest lsp-mode? It will automatically download and configure omnisharp. In case, it still does not work can you attach a sample project?

**Comment by razzmatazz** [comment]
The same thing happens to me. However if I refresh the file with C-x C-v AFTER the server has completely loaded, the issue goes away.

The actual issue *appears for me* to be that omnisharp-roslyn sends the response to `initialize` too early:
 - https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#initialize

I.e. it sends the response *before* it has finished loading all the projects on the solution, thus any requests lsp-mode sends before that is done are bound to fail in some way. For some larger solutions this might take a while and for the moment we don't have a way to know when except for watching when these (or similar) lines appear on *lsp-log*:
```
initialized...
(omnisharp/roslyn is still actually loading .csprojs at this point)
...
crashes to textDocument/signatureHelp are logged here
...
Successfully loaded project file '/Users/bob/src/omnisharp/test/test.csproj'.
Adding project '/Users/bob/src/omnisharp/test/test.csproj'
Update project: test
...
```

There has been a couple of issued registered on omnisharp-roslyn repo on this:
 - https://github.com/OmniSharp/omnisharp-roslyn/issues/1245
 - https://github.com/OmniSharp/omnisharp-roslyn/issues/1445
 - https://github.com/OmniSharp/omnisharp-roslyn/issues/1521
 - https://github.com/OmniSharp/omnisharp-roslyn/issues/1580

The same crash appears to be happending for @sebasmonia on https://github.com/emacs-lsp/lsp-mode/issues/1108#issuecomment-545482410

**Comment by yyoncho** [comment]
Thank  you @razzmatazz . Do you think we can create a workaround by waiting for "Successfully loaded project file" message or we should close the issue and wait for the upstream?

**Comment by razzmatazz** [comment]
IMHO fixing this upstream is a better approach, – I will try to register an issue and/or maybe a PR to omnisharp-roslyn once I understand what is actually wrong here..

**Comment by yyoncho** [comment]
> IMHO fixing this upstream is a better approach, – I will try to register an issue and/or maybe a PR to omnisharp-roslyn once I understand what is actually wrong here..

Ok. Then once you have a more details I suggest closing this issue and #1108 and adding a faq entry pointing to the upstream issue(and eventually mentioning that the user should wait for the loaded project message).

**Comment by lxbarbosa** [comment]
@razzmatazz @yyoncho 
Still happening with the latest version(1.34.9), reopening does, indeed, "fix" the issue!

**Comment by yyoncho** [comment]
@razzmatazz do you know if the upstream has been fixed?

**Comment by razzmatazz** [comment]
As far as I know — not yet (tested a couple of weeks ago)

Actually I have started writing my own lsp server for C# in the meantime — l as attempting to fix omnisharp is just too much mental load for me, the codebase is rather sophisticated/complicated.

https://github.com/razzmatazz/csharp-language-server

I forked lsp wiring off https://github.com/fsprojects/fsharp-language-server and things are surprising easy to implement. (I know Pareto rule will show its head eventually)

—Saulius Menkevičius

**Comment by yyoncho** [comment]
@razzmatazz that is cool. Feel free to link it from lsp-mode supported servers if you are looking for more contributors.

**Comment by razzmatazz** [comment]
It is really to early, basic things don’t work. But definitely will inform once I have something that works somewhat for me, — having something that works is better than nothing.

In the meantime I’m ok with using omnisharp-emacs w/omnisharp (non lsp Setup)

**Comment by lxbarbosa** [comment]
It _seems_ to be fixed in yesterday's release...

https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.34.14

At least, it yet again is feeding popup information and company completion correctly.

No need to reopen the file once project fully loaded.

Still, I had a few issues I will eventually be able to reproduce.

**Comment by lxbarbosa** [comment]
ops:

dotnet --version: 3.1.101
lsp commit: 9f2333b1d5213f651af643ec5f2876bd987d7ab1
Debian SID 11

**Comment by razzmatazz** [comment]
@lxbarbosa great! will take a look to confirm

**Comment by lxbarbosa** [comment]
Actually it's not working at all. LOL
Once it loads a project it reads and provide correct information to popup and sometimes company.

Changing the code and it is stuck with early "parsing"

eg: changing a string var to char and still shows the same early information. Same goes for company completions.

Well, its almost there :D

![stuck](https://i.ibb.co/BtS84TQ/shot-2020-3-12-4-51-26.png)

**Comment by gamedolphin** [comment]
It does not work for me either. It connects, but then nothing. Not even a popup or company. :(

**Comment by razzmatazz** [comment]
Yes, it still does not work. 

However, I noticed @david-driscoll and others are actively working on improving LSP part of Omnisharp so hopefully LSP w/ C# is comming eventually:
 - https://github.com/OmniSharp/csharp-language-server-protocol/commits/master

**Comment by razzmatazz** [comment]
I made a PR for omnisharp-roslyn that upgrades LSP component and fixes some of the issues (at least for me) -- now I have proper autocompletion context, flycheck, lenses and some other things working.
 - https://github.com/OmniSharp/omnisharp-roslyn/pull/1754

**Comment by lxbarbosa** [comment]
[v1.35.1](https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.35.1) released.

Most of its feature works correctly once `LSP` finishes loading it.

But it still unaware of any change in the file is made.

![method docstring](https://user-images.githubusercontent.com/40282381/81027665-feb6a080-8e54-11ea-9dcd-4a816f55edf3.png)

![completion](https://user-images.githubusercontent.com/40282381/81027769-4dfcd100-8e55-11ea-9611-0063beba6b61.png)

**Comment by razzmatazz** [comment]
@lxbarbosa yeah, that is because of omnisharp-roslyn LSP file sync issue. My PR to fix this is no longer WIP, -- hopefully maintainers of omnisharp-roslyn will take a look at that.

**Comment by lxbarbosa** [comment]
For those interested it seems it fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/1791

**Comment by sebasmonia** [comment]
Using a minimal project to test and building Omnisharp from `master`, I didn't get the proper list of completion candidates from for the BCL classes. :(

**Comment by Mallchad** [comment]
I don't know what's wrong on my end but omnisharp has hardly worked for me at all with lsp-mode.
It's showing hardly any capabilities even on the latest everything.
![image](https://user-images.githubusercontent.com/45771609/82126225-39003600-97a3-11ea-9a05-31a4bbe4086d.png)

**Comment by razzmatazz** [comment]
> I don't know what's wrong on my end but omnisharp has hardly worked for me at all with lsp-mode.
> It's showing hardly any capabilities even on the latest everything.
> ![image](https://user-images.githubusercontent.com/45771609/82126225-39003600-97a3-11ea-9a05-31a4bbe4086d.png)

Thats the features omnisharp exposes over LSP. It is not a configuration issue on your part but rather an issue of incomplete implementation. I have a PR to add support for “textDocument/codeActions” though:
 - https://github.com/OmniSharp/omnisharp-roslyn/pull/1795

LSP is/was second-class protocol for omnisharp-roslyn, as most of development has until now been focused on exposing features over the native protocol (used by omnisharp-vscode, omnisharp-emacs, omnisharp-atom, etc.)

**Comment by razzmatazz** [comment]
I have also added another handler for the `workspace/symbol` request in this PR:
 - https://github.com/OmniSharp/omnisharp-roslyn/pull/1799

**Comment by lxbarbosa** [comment]
Pre-release of v1.35.2 with @razzmatazz PRs is out.

https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.35.2

**Comment by razzmatazz** [comment]
Uh, they didn’t merge the code actions and workspace symbols handlers yet.. but the sync issue should be fixed finally though.

**Comment by lxbarbosa** [comment]
@razzmatazz 
That's more than enough to turn Emacs my favorite C# IDE :)

**Comment by Mallchad** [comment]
Can confirm the latest update does solve most issues.
Although...
I found out that part of my problems with due to an sln/csproj (maybe out of date, maybe corrupted? idk) completely blocking any of the other features from working as well, I have no idea what that was all about.
I am happy now, thanks for your hard work guys!

**Comment by lxbarbosa** [comment]
@Mallchad 
Which features are still not working? a new toy project of mine, net core 3.1.4, "is working fine in my computer" :)

**Comment by gamedolphin** [comment]
This is wonderful. Thank you! It works like a charm. Bye bye omnisharp-emacs? Most probably.

**Comment by razzmatazz** [comment]
> This is wonderful. Thank you! It works like a charm. Bye bye omnisharp-emacs? Most probably.

I am planning to deprecate omnisharp-emacs eventually, but some features are still not working with LSP. At least the ones that I use :) -- e.g. running unit test(s). Thus I am kind of reluctant to declare a victory yet.

I am starting to implement some of those things (unit test running on queue):
 - https://github.com/OmniSharp/omnisharp-roslyn/pull/1807

**Comment by Mallchad** [comment]
@razzmatazz I agree it is good but there is still a lot of work to be done.
Especially when you compare the capabilities to clangd (which is feature rich).
Currently I'm not noticing much that I would miss aside from symbol highlighting, I can live without 
this though.

@lxbarbosa as to answer your question the one thing that doesn't necessarily work is external libraries, particularly UnityEditor.dll
But this was always problematic.

**Comment by sebasmonia** [comment]
> I am planning to deprecate omnisharp-emacs eventually, but some features are still not working with LSP. At least the ones that I use :) -- e.g. running unit test(s). Thus I am kind of reluctant to declare a victory yet.

To run unit tests in using dotnet.el. It's not perfect, and many times I've toyed with the idea of a mega submission or creating a new package. But, it works!

**Comment by lxbarbosa** [comment]
@sebasmonia 
One idea I had is to bring to emacs a few essential Visual Studio/Rider features as Method extract, inserting Constructor, automatically creating method as we add a new parameter, format document...

I wonder if it would be better a CLI tool instead of an emacs package.

**Comment by Mallchad** [comment]
Part of this functionality is already facilitated with packages like
yasnippet and the codelens server capability that has been wired up in
razzmatazz' PR omnisharp-roslyn/#1799
I think automatic method creation is probably well out of the scope of this
project.
Formatting document is something that emacs provides in a light way by
default, mainly through indentation,
but there could be a code formater from omnisharp wired up, but I don't
know if that implementation actually existed to begin with.

**Comment by lxbarbosa** [comment]
@Mallchad 

**Snippets**:
I've PR yasnippets-snippets that add more snippets, clean existent ones after VS/Rider traditional snippets but its maintainer seems to be away lately. 
https://github.com/AndreaCrotti/yasnippet-snippets/pull/378

**Format Document**: Its kinda just indentation, what I mean is following .NET standards as:
- Indentation
`{get; set;}` to { get; set; } or  `foreach (...)` to `foreach(...)`
...

Other features that I miss in emacs are:

- Naming conventions  Tips
- Refactoring Tips
- Nuget package
- .NET project scaffolding
- .csproj pretty interface UI as `Guix.el`

**Comment by razzmatazz** [comment]
> @sebasmonia
> One idea I had, more a wish to be fair, is to bring to Emacs a few essential Visual Studio/Rider features as:
> 
> * Method extract,
> * Generate Constructor,
> * Creating a new method referenced by a new parameter,
> * Format document,
> * New Classes file creation
> * NuGet packages package (Guix.el is a good example)
> 
> Those features hardly will be in the scope of LSP servers, though!
> 
> I wonder if it would be better a CLI tool instead of an Emacs package.

Actually, most of the functionality you listed above has already been available in omnisharp-roslyn and will be available on next Roslyn release (the code actions PR has been merged already)

So it is closer than you think :)

**Comment by lxbarbosa** [comment]
@razzmatazz 
Awesome. It's been a perfect month, ignore that, of course!  :)
