### ISSUE TITLE
"Error: Variable binding depth exceeds max-specpdl-size" under heavy load

### ISSUE THREAD

**Issue by jaelsasser** [emacs-lsp/lsp-mode#182]
I'm hitting this error while playing around with [cquery](https://github.com/jacobdufault/cquery) and a large project, which dumps a couple thousand progress messages at the Emacs LSP client when it's starting up the workspace.

Using the latest Emacs 26.0.90 nightly. I'm able to consistently reproduce with lsp-mode from master.

```
error in process filter: progn: Error parsing language server output: (error Variable binding depth exceeds max-specpdl-size)
error in process filter: Error parsing language server output: (error Variable binding depth exceeds max-specpdl-size)
error in process filter: progn: Error parsing language server output: (error No Content-Length header)
error in process filter: Error parsing language server output: (error No Content-Length header)
error in process filter: progn: Error parsing language server output: (error Variable binding depth exceeds max-specpdl-size)
error in process filter: Error parsing language server output: (error Variable binding depth exceeds max-specpdl-size)
error in process filter: progn: Error parsing language server output: (error Variable binding depth exceeds max-specpdl-size)
error in process filter: Error parsing language server output: (error Variable binding depth exceeds max-specpdl-size)
error in process filter: progn: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
error in process filter: run-at-time: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
```

**Comment by jaelsasser** [comment]
Brought this issue up on the the Emacs IRC to see if my suspicion was right. There's a chance that [calling accept-process-output](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-receive.el#L265-L266) in our process filter function could trigger an unbounded recursion if `(lsp--parser-waiting-for-response p)` isn't cleared in a timely fashion.

**Comment by vibhavp** [comment]
Is this bug still present?

**Comment by jaelsasser** [comment]
Yes, it is. I've been running cquery with progress messages disabled, but when I toggle the indexing updates back on try and perform an LSP action on a large project (i.e. linux kernel), this pops up.

I have a local branch with the synchronous actions rewritten to loop on `accept-process-output` when they need to fetch a response to continue, but it occasionally fails when the existing recursive loop succeeds. Haven't had time to sort those yet.

**Comment by sebastiansturm** [comment]
I ran into the same issue after disabling cquery progress messages today. Unfortunately I'm not sure what's happening since emacs locks up completely and I haven't been able to get a stack trace so far. Also, your IRC link 404s on me; do you know if that discussion has been archived somewhere?
After reading your problem description, I assume that emacs recursively descends into `(accept-process-output proc)` within `lsp-io.el:lsp--parser-make-filter`; is that correct? Lacking a proper solution, I defined a global guard variable that prohibits recursive invocations of `(accept-process-output proc)`. It seemed to help, but without a proper understanding of the underlying issue I have no idea if that was coincidental or not.
What do you think would be the best way to resolve this?

**Comment by sebastiansturm** [comment]
also, are you planning to publish your modified branch (even if it's still work in progress)?

**Comment by jaelsasser** [comment]
Yeah, that's the offending call. Unfortunately my branch is significantly out of date. All of my work was back before `lsp-io.el` existed, and I'm not sure when I'll have time to clean up those patches. I'd like to do it right and extend the response-callback logic to also handle the just-return-from-the-function case, otherwise `lsp-mode`'s going to end up with two parallel sets of logic to handle transactions.

In the meantime, though, I've been using [a pretty hacky workaround](https://github.com/jaelsasser/dotfiles/blob/951282be2253c4617056e963248c058f3d7865de/emacs/init.el#L407) to ensure that I never hit this with `lsp-mode`. It significantly bumps up the Emacs recursion limit.

(Also, you won't be able to get a stack trace for this particular issue -- one of the annoying side-effects of erroring out in this manner is that Emacs can't generate a backtrace.)

**Comment by vibhavp** [comment]
Could you test this branch and see whether this bug still persists: https://github.com/emacs-lsp/lsp-mode/tree/rework-response-wait

**Comment by terlar** [comment]
This seems to have improved the situation, I usually got this error when looking up references with the lsp-javascript package really quickly after opening the project before everything was loaded. Now it only froze for a bit and eventually worked. However I saw these in the logs:

```
error in process filter: json-read: JSON readtable error
error in process filter: JSON readtable error
error in process filter: Error parsing language server output: (error No Content-Length header) [2 times]
```

But other than the temporary freeze didn't really affect the user experience as the lookup worked. However when this happens it seems the references also includes the definition, but next time I run it will properly only show the references.

**Comment by vibhavp** [comment]
AFAICT, the `lsp-javascript` error is because of a bug under discussion in https://github.com/emacs-lsp/lsp-mode/pull/251.

@jaelsasser Can you try reproducing the error in `lsp-cquery` with this branch?

**Comment by sebastiansturm** [comment]
tried it with cquery today and the original bug seems to have been solved. It seems, however, that `lsp-mode` may now truncate its response to user commands; is that to be expected? My test case consists of `lsp-ui-imenu` being invoked on a very large source file. With the default branch of `lsp-mode`, this triggered the `max-specpdl-size` bug every time whereas with the new branch, the imenu is shown almost immediately but contains only a small subset of the expected entries

**Comment by jaelsasser** [comment]
@vibhavp ran that branch today while working, plus I dropped the `max-specpdl-size` bump from my init.el. Your branch seems like a solid fix to me.

cquery's started [rate-limiting their progress message](https://github.com/cquery-project/cquery/commit/512d2b5213d392e7f399e5b40a200b0baf18c39c) in the meantime, though, so I can't guarantee that I stressed Emacs as hard as I used to.

**Comment by vibhavp** [comment]
@sebastiansturm lsp--send-wait doesn't change the response output. That is an issue with the language server.

Thanks for testing the fix, I'll merge this branch.

**Comment by jaelsasser** [comment]
@vibhavp: Flipped back to tracking the master branch this weekend… can confirm that, with lsp-cquery, I *definitely* still get this issue without your `rework-response-wait` branch.

**Comment by Yevgnen** [comment]
I got this when company-lsp is starting to do completion...
