### ISSUE TITLE
LSP Mode with gopls timing out on Windows Emacs 27.1

### ISSUE THREAD

**Issue by vamsi360** [emacs-lsp/lsp-mode#2268]
**Describe the bug**
On Windows 10, I am currently running Emacs 27.1 with latest lsp-mode from MELPA. I use it with gopls@latest installed and is in the path.
Whenever I goto the project from Emacs and navigate inside a method in go code, the call gets stuck and I get a timeout message:
`progn: Timeout while waiting for response. Method: textDocument/definition.`

I have checked if its an issue in configuration -> I can reproduce the same with prelude lsp mode with gopls as well.

**To Reproduce**
Open a go project with lsp-mode and gopls on Windows, navigage to any codeblock and jump into a function -> the call should get stuck.

**Expected behavior**
Navigation should be smooth.

**Which Language Server did you use**
lsp-go: 20201016.1633
gopls: 
`❯❯ gopls version
golang.org/x/tools/gopls v0.5.1
    golang.org/x/tools/gopls@v0.5.1 h1:AF3Uh7HF08SZpKFfgJO6zfF3bbxyDXWqdkK4kMXiQ1o=
`

**OS**
Windows 10

**Error callstack**
`Debugger entered--Lisp error: (error "Timeout while waiting for response. Method: textDo...")
  signal(error ("Timeout while waiting for response. Method: textDo..."))
  error("Timeout while waiting for response. Method: %s." "textDocument/definition")
  (progn (error "Timeout while waiting for response. Method: %s." method))
  (if (< expected-time (time-to-seconds (current-time))) (progn (error "Timeout while waiting for response. Method: %s." method)))
  (while (not (or resp-error resp-result)) (accept-process-output nil 0.001) (if (< expected-time (time-to-seconds (current-time))) (progn (error "Timeout while waiting for response. Method: %s." method))))
  (progn (lsp-request-async method params #'(lambda (res) (setq resp-result (or res :finished))) :error-handler #'(lambda (err) (setq resp-error err)) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (accept-process-output nil 0.001) (if (< expected-time (time-to-seconds (current-time))) (progn (error "Timeout while waiting for response. Method: %s." method)))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error (lsp:json-error-message resp-error))) (t (error (lsp:json-error-message (cl-first resp-error))))))
  (unwind-protect (progn (lsp-request-async method params #'(lambda (res) (setq resp-result (or res :finished))) :error-handler #'(lambda (err) (setq resp-error err)) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (accept-process-output nil 0.001) (if (< expected-time (time-to-seconds (current-time))) (progn (error "Timeout while waiting for response. Method: %s." method)))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error (lsp:json-error-message resp-error))) (t (error (lsp:json-error-message (cl-first resp-error)))))) (if done\? nil (lsp-cancel-request-by-token :sync-request)))
  (let* ((send-time (time-to-seconds (current-time))) (expected-time (+ send-time lsp-response-timeout)) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'(lambda (res) (setq resp-result (or res :finished))) :error-handler #'(lambda (err) (setq resp-error err)) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (accept-process-output nil 0.001) (if (< expected-time (time-to-seconds (current-time))) (progn (error "Timeout while waiting for response. Method: %s." method)))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error (lsp:json-error-message resp-error))) (t (error (lsp:json-error-message (cl-first resp-error)))))) (if done\? nil (lsp-cancel-request-by-token :sync-request))))
  (if no-wait (lsp-notify method params) (let* ((send-time (time-to-seconds (current-time))) (expected-time (+ send-time lsp-response-timeout)) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'(lambda (res) (setq resp-result ...)) :error-handler #'(lambda (err) (setq resp-error err)) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (accept-process-output nil 0.001) (if (< expected-time (time-to-seconds ...)) (progn (error "Timeout while waiting for response. Method: %s." method)))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error (lsp:json-error-message resp-error))) (t (error (lsp:json-error-message ...))))) (if done\? nil (lsp-cancel-request-by-token :sync-request)))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:no-wait :no-merge :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:no-wait :no-merge..." (car --cl-keys--)))))) (if no-wait (lsp-notify method params) (let* ((send-time (time-to-seconds (current-time))) (expected-time (+ send-time lsp-response-timeout)) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'(lambda ... ...) :error-handler #'(lambda ... ...) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (accept-process-output nil 0.001) (if (< expected-time ...) (progn ...))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error ...)) (t (error ...)))) (if done\? nil (lsp-cancel-request-by-token :sync-request))))))
  (let* ((no-wait (car (cdr (plist-member --cl-rest-- ':no-wait)))) (no-merge (car (cdr (plist-member --cl-rest-- ':no-merge))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:no-wait :no-merge..." (car --cl-keys--)))))) (if no-wait (lsp-notify method params) (let* ((send-time (time-to-seconds (current-time))) (expected-time (+ send-time lsp-response-timeout)) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'... :error-handler #'... :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not ...) (accept-process-output nil 0.001) (if ... ...)) (setq done\? t) (cond (... nil) (resp-result resp-result) (... ...) (t ...))) (if done\? nil (lsp-cancel-request-by-token :sync-request)))))))
  lsp-request("textDocument/definition" (:textDocument (:uri "file:///d%3A/code/src/gocode/src/github.com/hotsta...") :position (:line 238 :character 29)))
  (lsp--locations-to-xref-items (lsp-request "textDocument/definition" (lsp--text-document-position-params)))
  (save-excursion (if (get-text-property 0 'identifier-at-point identifier) nil (goto-char (cl-rest (or (assoc identifier lsp--symbols-cache) (user-error "Unable to find symbol %s in current document" identifier))))) (lsp--locations-to-xref-items (lsp-request "textDocument/definition" (lsp--text-document-position-params))))
  (progn (save-excursion (if (get-text-property 0 'identifier-at-point identifier) nil (goto-char (cl-rest (or (assoc identifier lsp--symbols-cache) (user-error "Unable to find symbol %s in current document" identifier))))) (lsp--locations-to-xref-items (lsp-request "textDocument/definition" (lsp--text-document-position-params)))))
  (closure (company-mode cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines dap-ui-menu-items company-backends t) (_backend identifier) (progn (save-excursion (if (get-text-property 0 'identifier-at-point identifier) nil (goto-char (cl-rest (or ... ...)))) (lsp--locations-to-xref-items (lsp-request "textDocument/definition" (lsp--text-document-position-params))))))(xref-lsp #("NewDBConnector" 0 14 (identifier-at-point t fontified t face font-lock-function-name-face)))
  apply((closure (company-mode cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines dap-ui-menu-items company-backends t) (_backend identifier) (progn (save-excursion (if (get-text-property 0 'identifier-at-point identifier) nil (goto-char (cl-rest (or ... ...)))) (lsp--locations-to-xref-items (lsp-request "textDocument/definition" (lsp--text-document-position-params)))))) xref-lsp #("NewDBConnector" 0 14 (identifier-at-point t fontified t face font-lock-function-name-face)))
  xref-backend-definitions(xref-lsp #("NewDBConnector" 0 14 (identifier-at-point t fontified t face font-lock-function-name-face)))
  #f(compiled-function () #<bytecode 0x4f00b5d>)()
  xref--show-defs-buffer(#f(compiled-function () #<bytecode 0x4f00b5d>) ((window . #<window 3 on server.go>) (display-action)))
  xref--show-defs(#f(compiled-function () #<bytecode 0x4f00b5d>) nil)
  xref--find-definitions(#("NewDBConnector" 0 14 (identifier-at-point t fontified t face font-lock-function-name-face)) nil)
  xref-find-definitions(#("NewDBConnector" 0 14 (identifier-at-point t fontified t face font-lock-function-name-face)))
  funcall-interactively(xref-find-definitions #("NewDBConnector" 0 14 (identifier-at-point t fontified t face font-lock-function-name-face)))
  #<subr call-interactively>(xref-find-definitions nil nil)
  apply(#<subr call-interactively> xref-find-definitions (nil nil))
  (let ((ido-cr+-current-command command)) (apply orig-fun command args))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> xref-find-definitions nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (xref-find-definitions nil nil))
  call-interactively(xref-find-definitions nil nil)
  command-execute(xref-find-definitions)
`

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by kiennq** [comment]
Not sure if this is issue of `lsp-mode`, `gopls` cannot return result on time so `lsp-mode` time outed.
Does this happens frequently? What happens if you try with release version of `gopls` instead of `latest`?

**Comment by vamsi360** [comment]
Hi @kiennq I have tried with 0.4.4 and 0.5.0 as well and notice the same issue.
`go get golang.org/x/tools/gopls@v0.4.4`

lsp-log below:

```
Go info
-------
go version go1.14.10 windows/amd64
Cancelling textDocument/documentLink(27) in hook post-command-hook
Cancelling textDocument/codeAction(26) in hook post-command-hook
Cancelling textDocument/documentLink(22) in hook post-command-hook
Cancelling textDocument/documentLink(16) in hook post-command-hook
Cancelling textDocument/documentLink(7) in hook post-command-hook
Cancelling textDocument/documentLink(4) in hook post-command-hook
```

Also, when I use VSCode with the same gopls, it works fine.

**Comment by kiennq** [comment]
Can you turn `toggle-debug-on-error` to see when the error happens?

**Comment by vamsi360** [comment]
@kiennq Please find the error below when toggle is enabled
```
Debugger entered--Lisp error: (error "Timeout while waiting for response. Method: textDo...")
  signal(error ("Timeout while waiting for response. Method: textDo..."))
  error("Timeout while waiting for response. Method: %s." "textDocument/definition")
  lsp-request("textDocument/definition" (:textDocument (:uri "file:///d%3A/code/src/gocode/src/github.com/hotsta...") :position (:line 47 :character 18)))
  #f(compiled-function (backend identifier) #<bytecode 0x2016a6d>)(xref-lsp #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  apply(#f(compiled-function (backend identifier) #<bytecode 0x2016a6d>) xref-lsp #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  xref-backend-definitions(xref-lsp #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  #f(compiled-function () #<bytecode 0x41063e1>)()
  xref--show-defs-buffer(#f(compiled-function () #<bytecode 0x41063e1>) ((window . #<window 3 on server.go>) (display-action)))
  xref--show-defs(#f(compiled-function () #<bytecode 0x41063e1>) nil)
  xref--find-definitions(#("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)) nil)
  xref-find-definitions(#("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  funcall-interactively(xref-find-definitions #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  #<subr call-interactively>(xref-find-definitions nil nil)
  apply(#<subr call-interactively> xref-find-definitions (nil nil))
  (let ((ido-cr+-current-command command)) (apply orig-fun command args))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> xref-find-definitions nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (xref-find-definitions nil nil))
  call-interactively(xref-find-definitions nil nil)
  command-execute(xref-find-definitions)
```

**Comment by kiennq** [comment]
Btw, what's your value of `lsp-response-timeout`?

**Comment by vamsi360** [comment]
The value is 10

```
lsp-response-timeout is a variable defined in ‘lsp-mode.el’.
Its value is 10

  You can customize this variable.

Documentation:
Number of seconds to wait for a response from the language server before timing out.

```

**Comment by vamsi360** [comment]
The error while opening the project.

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("com\\companyname\\project-name" nil nil)
  ht-get(nil "com\\companyname\\project-name")
  (setq table (ht-get table (car-safe (prog1 keys (setq keys (cdr keys))))))
  (while keys (setq table (ht-get table (car-safe (prog1 keys (setq keys (cdr keys)))))))
  ht-get*(#<hash-table equal 0/65 0x3bcf881> "gopls-D:\\code\\src\\gocode\\src\\github" "com\\companyname\\project-name")
  apply(ht-get* (#<hash-table equal 0/65 0x3bcf881> "gopls-D:\\code\\src\\gocode\\src\\github" "com\\companyname\\project-name"))
  #f(compiled-function (input0) #<bytecode 0x204665d>)(#<hash-table equal 2/2 0x3bcf36d>)
  mapcar(#f(compiled-function (input0) #<bytecode 0x204665d>) [#<hash-table equal 2/2 0x3bcf319> #<hash-table equal 2/2 0x3bcf36d>])
  -map(#f(compiled-function (input0) #<bytecode 0x204665d>) [#<hash-table equal 2/2 0x3bcf319> #<hash-table equal 2/2 0x3bcf36d>])
  lsp--build-workspace-configuration-response(#<hash-table equal 1/1 0x3bcf2e9>)
  lsp--on-request(#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 20/20 0x3ae6669> :registered-server-capabilities nil :root "d:/code/src/gocode/src/github.com/companyname/persona-..." :client #s(lsp--client :language-id "go" :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x3914a31>) :test\? #f(compiled-function () #<bytecode 0x3914a49>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x3914a55> :request-handlers #<hash-table equal 0/65 0x3914c85> :response-handlers #<hash-table eql 4/65 0x3914ca5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x3915305> :action-handlers #<hash-table equal 0/65 0x391721d> :major-modes (go-mode) :activation-fn nil :priority 0 :server-id gopls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn lsp-go--library-default-directories :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn #f(compiled-function () #<bytecode 0x39149a1>) :async-request-handlers #<hash-table equal 0/65 0x391744d> :download-server-fn nil :download-in-progress? nil :buffers nil) :host-root nil :proc #<process gopls> :cmd-proc #<process gopls> :buffers (#<buffer server.go>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x3a159a1> :watches #<hash-table equal 0/65 0x3a15bd1> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x3a15bf1> :work-done-tokens #<hash-table equal 0/65 0x3a15c11>) #<hash-table equal 4/4 0x3bcf285>)
  lsp--parser-on-message(#<hash-table equal 4/4 0x3bcf285> #s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 20/20 0x3ae6669> :registered-server-capabilities nil :root "d:/code/src/gocode/src/github.com/companyname/persona-..." :client #s(lsp--client :language-id "go" :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x3914a31>) :test\? #f(compiled-function () #<bytecode 0x3914a49>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x3914a55> :request-handlers #<hash-table equal 0/65 0x3914c85> :response-handlers #<hash-table eql 4/65 0x3914ca5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x3915305> :action-handlers #<hash-table equal 0/65 0x391721d> :major-modes (go-mode) :activation-fn nil :priority 0 :server-id gopls :multi-root nil :initialization-options nil :custom-capabilities nil :library-folders-fn lsp-go--library-default-directories :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn #f(compiled-function () #<bytecode 0x39149a1>) :async-request-handlers #<hash-table equal 0/65 0x391744d> :download-server-fn nil :download-in-progress? nil :buffers nil) :host-root nil :proc #<process gopls> :cmd-proc #<process gopls> :buffers (#<buffer server.go>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x3a159a1> :watches #<hash-table equal 0/65 0x3a15bd1> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x3a15bf1> :work-done-tokens #<hash-table equal 0/65 0x3a15c11>))
  #f(compiled-function (proc input) #<bytecode 0x3a15441>)(#<process gopls> "Content-Length: 340\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"...")
```

**Comment by vamsi360** [comment]
@kiennq the above trace points that the escaping of the project dir is not working correctly in lsp-mode.el while giving to ht-get function.
Ex: github.com is split into two strings above in ht-get

**Comment by yyoncho** [comment]
should be fixed by https://github.com/emacs-lsp/lsp-mode/pull/2258/files

**Comment by vamsi360** [comment]
Hi thanks @yyoncho , when will the pkg be release to MELPA?

**Comment by kiennq** [comment]
Unless if you on MELPA stable, the latest one should be available on MELPA after 2, 3 hours

**Comment by vamsi360** [comment]
Hi Thanks. I upgraded to the latest version in MELPA. The startup error above went away but the actual issue of timing out is still happening.

```
Debugger entered--Lisp error: (error "Timeout while waiting for response. Method: textDo...")
  signal(error ("Timeout while waiting for response. Method: textDo..."))
  error("Timeout while waiting for response. Method: %s." "textDocument/definition")
  lsp-request("textDocument/definition" (:textDocument (:uri "file:///d%3A/code/src/gocode/src/github.com/hotsta...") :position (:line 47 :character 20)))
  #f(compiled-function (backend identifier) #<bytecode 0x229e405>)(xref-lsp #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  apply(#f(compiled-function (backend identifier) #<bytecode 0x229e405>) xref-lsp #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  xref-backend-definitions(xref-lsp #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  #f(compiled-function () #<bytecode 0x3c4a9ed>)()
  xref--show-defs-buffer(#f(compiled-function () #<bytecode 0x3c4a9ed>) ((window . #<window 3 on server.go>) (display-action)))
  xref--show-defs(#f(compiled-function () #<bytecode 0x3c4a9ed>) nil)
  xref--find-definitions(#("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)) nil)
  xref-find-definitions(#("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  funcall-interactively(xref-find-definitions #("NewABService" 0 12 (identifier-at-point t fontified t face font-lock-function-name-face)))
  #<subr call-interactively>(xref-find-definitions nil nil)
  apply(#<subr call-interactively> xref-find-definitions (nil nil))
  (let ((ido-cr+-current-command command)) (apply orig-fun command args))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> xref-find-definitions nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (xref-find-definitions nil nil))
  call-interactively(xref-find-definitions nil nil)
  command-execute(xref-find-definitions)
```

**Comment by vamsi360** [comment]
Hi @kiennq @yyoncho 

There was a mistake with GOROOT path and once that is fixed, with the latest lsp-mode, its working correctly for me. Thanks a lot for fixing this and helping me. Closing the issue.
