### ISSUE TITLE
wrong place for Cargo.toml

### ISSUE THREAD

**Issue by davemilter** [emacs-lsp/lsp-mode#42]
I use today repo of rls (88fc39bd654c536b4f8f1cd1fc8245706f0284ec), and emacs 25.1.1 on linux amd64.

I create project boo:

`cargo new boo
`

and open `src/lib.rs` in emacs and all freezes,
Rust Language Server stderr buffer contains:

```
thread '<unnamed>' panicked at 'could not create cargo workspace: ChainedError { error: failed to read `/tmp/boo/src/Cargo.toml`, cause: No such file or directory (os error 2) }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'could not create cargo workspace: ChainedError { error: failed to read `/tmp/boo/src/Cargo.toml`, cause: No such file or directory (os error 2) }', /checkout/src/libcore/result.rs:859 
```

I not undernstad, why emacs+rls open `Cargo.toml` in `src`, while it should look it at `/tmp/boo/Cargo.toml`?

**Comment by vibhavp** [comment]
Have you tried updating your lsp-mode package? I fixed that issue recently.

**Comment by davemilter** [comment]
lsp-mode           20170405.1945 installed, list-package reports that there are no updates

**Comment by tutysara** [comment]
Melpa get the updates slowly sometimes, if you are using spacemacs you can install the package from github directly using -- ` (lsp-mode :location (recipe
                                                           :fetcher github
                                                           :repo "vibhavp/emacs-lsp"))
` in additional packages list

**Comment by davemilter** [comment]
Finally I got update from melpa, and I am using lsp-mode   20170407.7 now,
but error still here:

thread '<unnamed>' panicked at 'could not create cargo workspace: ChainedError { error: failed to read `/tmp/boo/src/Cargo.toml`, cause: No such file or directory (os error 2) }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'could not create cargo workspace: ChainedError { error: failed to read `/tmp/boo/src/Cargo.toml`, cause: No such file or directory (os error 2) }', /checkout/src/libcore/result.rs:859

I also update rls to today version commit 32cd023ef6c70e9819a6743807510315497978f5

**Comment by davemilter** [comment]
@vibhavp I clone emacs-lsp repo(6abc9d6673678f63b64fb47f9aa89af4b42a9be0) and compare it with elpa/lsp-mode-20170407.7. All files are the same. So I got the recent version.
But bug still here.

Plus I install vscode, and it works fine with `rls`

**Comment by Dushistov** [comment]
I faced with the same problem.

I hacked it like this:

```
modified   lsp-mode.el
@@ -95,7 +95,7 @@ Optional arguments:
 	  "--release")
       "rls")))
 
-(lsp-define-client 'rust-mode "rust" 'stdio #'(lambda () default-directory)
+(lsp-define-client 'rust-mode "rust" 'stdio #'(lambda () "/tmp/foo")
                    :command (lsp--rust-rls-command)
                    :name "Rust Language Server")
 

```

@vibhavp  @tutysara May be problem in [rls](https://github.com/rust-lang-nursery/rls)
version, I used recent one rust-lang-nursery/rls@016cbc5, what version do you use?

Because, even after fix, I got strange messages:

> Unkown method: rustDocument/diagnosticsBegin [2 times]
> Unkown method: rustDocument/diagnosticsEnd [2 times]

**Comment by vibhavp** [comment]
I'm not getting this error on my machine, though. Which directory are you opening `lib.rs` from?

**Comment by Dushistov** [comment]
@vibhavp I start `emacs` from `$HOME`, test project in `/tmp/foo`:

`evgeniy@localhost ~ $ emacs-25 /tmp/foo/src/lib.rs &`

> I'm not getting this error on my machine. Which directory are you opening lib.rs from?

but start directory not important, for example if I change code like this:

```
(lsp-define-client 'rust-mode "rust" 'stdio #'(lambda () (progn (message "!!!! %s" default-directory) "/tmp/foo"))
                   :command (lsp--rust-rls-command)
                   :name "Rust Language Server")
```

it prints in `*Messages*`

`!!!! /tmp/foo/src/
`
when I started from `/home/evgeniy`,
and when I started from `/tmp/foo`

May be version of emacs is importand, I use GNU Emacs 25.1 on Linux

**Comment by vibhavp** [comment]
I just updated rls and I encoutner this bug too. I'm not sure if this is an issue with rls or `emacs-lsp`.

**Comment by davemilter** [comment]
@vibhavp 

>I just updated rls and get this bug. I'm not sure if this is an issue with rls or emacs-lsp.

vscode works with recent `rls`

**Comment by vibhavp** [comment]
`lsp-rust` uses `cargo locate-project` now, so this should no longer be an issue.
