### ISSUE TITLE
Point moves to sideline

### ISSUE THREAD

**Issue by pcr910303** [emacs-lsp/lsp-mode#724]
**Describe the bug**
The point moves to sideline and text is input there.

**To Reproduce**
Open a new cpp file(with clangd as lsp server). Type in `#include <io`.
Wait for a while. Type in `st`. `st` is input(first) after the sideline, and moved after some delay

**Expected behavior**
`st` should be input in place, not in sideline

**Which Language Server did you use**
clangd

**OS**
macOS

![out](https://user-images.githubusercontent.com/37990858/54662913-f1d8cf80-4b22-11e9-8417-e8fe6926b11f.gif)

**Comment by yyoncho** [comment]
(cc @sebastiencs )

**Comment by pcr910303** [comment]
Another GIF that illustrates the problem... :-(

![output-2019-03-28-08:48:05](https://user-images.githubusercontent.com/37990858/55120153-273f7780-5138-11e9-8b45-491a4f1ec632.gif)

**Comment by sebastiencs** [comment]
@pcr910303 Fixed in https://github.com/emacs-lsp/lsp-ui/commit/92b4d4e722d5214e025cef65099ae3ccd914157c

**Comment by pcr910303** [comment]
@sebastiencs Thanks for the fix!
I'm not sure if opening a new issue would be better, but the fix (that disallows prompts to be displayed in current line) breaks
* when the current line is last line and there is no newline -> sideline is displayed on the current line(which makes this problem persist)
* when the current line is last line and there is newline -> prompt wrapping happens and break.

This is a gif for illustrating the problem.
![output-2019-03-29-09:51:12](https://user-images.githubusercontent.com/37990858/55202045-11e64e00-5209-11e9-9e06-945ec8636759.gif)

**Comment by sebastiencs** [comment]
@pcr910303 Thanks, can you test https://github.com/emacs-lsp/lsp-ui/commit/d4088c7471bdb3ba95f2fb0b60277ad95b34a25f

**Comment by yyoncho** [comment]
@pcr910303 closing the issue after @sebastiencs fixes(it case you still have problems, please open a new issue in lsp-ui project).
