### ISSUE TITLE
lsp doc render

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#883]
I am using a several LSP servers/clients in my daily work. For some lang servers, the doc strings are rendered as markdown or lang-mode perfectly (e.g. rls, pyls, etc.).

- rls
![image](https://user-images.githubusercontent.com/140797/59511061-e7429200-8ee7-11e9-82e3-d0d93497ce35.png)

But for some other lang servers, the doc strings are not redered, e.g. gopls, mspyls, etc. 

- mspyls
![image](https://user-images.githubusercontent.com/140797/59511046-d6921c00-8ee7-11e9-9252-fe8fbcb5cf09.png)

Another fact is the dco strings are displayed perfectly in VSCode, even the same lang servers. So, it seems a compatibility issue of lsp-mode.

**Comment by yyoncho** [comment]
I have fixed the issue for gopls, please test with the rest of the servers. But  there is one more issue in lsp-ui which cannot display `---` very well. I am looking into it.

**Comment by seagle0128** [comment]
Thanks for the quick fixing!

Now it looks like this. It seems not working.

![image](https://user-images.githubusercontent.com/140797/59554593-f143be00-8fd7-11e9-8cde-75455b4f1dcd.png)

**Comment by seagle0128** [comment]
Thanks for quick fixing!

Yes, it does work with `lsp-describe-thing-at-point` now, but not work well in `lsp-ui` and `company-box-doc`.

**Comment by yyoncho** [comment]
Can you give me sample python file for the last screenshot? Also, can you show me screeshots for lsp-ui as well. On my machine there is strange issue with the new lines.

**Comment by seagle0128** [comment]
Sample

```python
import pandas as pd
import matplotlib.pyplot as plt

output = pd.DataFrame()
plt.plot(output['line'])
plt.show()
```

without webkit: The position is invalid

![image](https://user-images.githubusercontent.com/140797/59555109-4257b000-8fe0-11e9-985e-461b2b2f0ffe.png)

with webkit:

![image](https://user-images.githubusercontent.com/140797/59555136-99f61b80-8fe0-11e9-886f-ccfaa87df3fc.png)

company-box-doc:

![image](https://user-images.githubusercontent.com/140797/59555171-03762a00-8fe1-11e9-8e73-675614ebea29.png)

**Comment by yyoncho** [comment]
I found the issue with completion, how do you get the `\*`?

**Comment by yyoncho** [comment]
Can you test with : https://github.com/emacs-lsp/lsp-mode/commit/767693b26712751354fb2bdc8b897924f123bbc4

**Comment by seagle0128** [comment]
@yyoncho new screenshot

![image](https://user-images.githubusercontent.com/140797/59564589-1fc6a500-907b-11e9-9822-98c94ba4993f.png)

Other issues still exist.

**Comment by yyoncho** [comment]
The issue with long separator line should be fixed too or at least I cannot reproduce it. I have tested yet with the xwidget.

**Comment by seagle0128** [comment]
@yyoncho Thank you! I meant the doc isn't rendered as markdown yet, and not perfect in xwidget. Others are fine now.

**Comment by yyoncho** [comment]
@seagle0128 I found what is causing these issues - I will try to provide a fix. The issue is that the overlays do not respect when invisible text property and I am stripping them. But this is causing issues when the for python ls.

**Comment by seagle0128** [comment]
@yyoncho It's almost perfect in `rls` and `jdtls`, but still not as good as in VSCode. For example:

![image](https://user-images.githubusercontent.com/140797/59623572-0bf86d00-9167-11e9-963f-9d1609a4a409.png)

**Comment by yyoncho** [comment]
IMO this is `markdown-mode` bug.
