### ISSUE TITLE
[Spacemacs] lsp-dart: completion quirks

### ISSUE THREAD

**Issue by dennismayr** [emacs-lsp/lsp-mode#907]
**Description**
`lsp` in `dart-mode` doesn't autocomplete as expected: either missing completion/suggestions, or malformed completions.

**To Reproduce**
Ubuntu 18.04, Emacs 26.2, Spacemacs _develop_ latest pull.
Type the following lines:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());
class MyApp extends StatelessWidget{
  @override
  Widget build(BuildContext context){
    
  }
}
```

Example: when entering `Widget build(BuildContext context)`, after typing `(Buildcon` (or a close variation) one expects to get `BuildContext` as suggestion. It does happen, as shown below:
![Imgur](https://imgur.com/IT3sCzV.png)

However, when selecting the suggestion (3 identical suggestions by name and class?), it's completed as `.prefix0.BuildContext` instead of `BuildContext`, plus an import line at the top (line 2)
![Imgur](https://imgur.com/AorzQs8.png)

**Expected behavior**
The code block should look like this
![Imgur](https://imgur.com/KW0dWXZ.png)

I'm not sure if the problem could be originated in `lsp`, `company-lsp` or the language server.

**Which Language Server did you use**
`dart_language_server 0.1.14`, `lsp-mode-20190624.942`

**Error callstack**
[lsp-log: dart_analysis_server](https://drive.google.com/open?id=1o3rjrJrAB2uMOOmmEwt1akxMQ-dog1H9) (zipped)

**Emacs options**
``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
@itome willing to take a look?

**Comment by yyoncho** [comment]
@dennismayr can you do `M-x company-diag` when before the completion and paste the output?

(cc @tigersoldier )

**Comment by itome** [comment]
@yyoncho @dennismayr OK, I'll check it.

**Comment by itome** [comment]
@dennismayr 
This seems to be dart-sdk issue -> https://github.com/dart-lang/sdk/issues/36890

**Comment by dennismayr** [comment]
@yyoncho Before completing `BuildContext`, here's `M-x company-diag` output at `Build`:

```elisp
Emacs 26.2 (x86_64-pc-linux-gnu) of 2019-04-12 on lgw01-amd64-060
Company 0.9.10

company-backends: (company-lsp php-extras-company company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-files
             (company-dabbrev-code company-gtags company-etags company-keywords)
             company-oddmuse company-dabbrev)

Used backend: company-lsp
Major mode: dart-mode
Prefix: (#("Build" 0 5
   (fontified t face font-lock-type-face))
 . t)

Completions: none(error fetching)
```

Also, when typing basic, recurring syntax such as `class`, `build`, `extends`, they're not suggested even as quick _tab-completion_, which does happen with `Go` and `rust` modes + `lsp`. Still, something one can live without, only that it makes development a tad faster (like in VSCode).

`dart` completion in Emacs has a significant lag (about 2 seconds on an _i5_ laptop).

@itome Do you think it's related to `dart-sdk` and its language server too?

Anyway, thank you so much for the input!
Let me know what else I can provide to debug the issue.
If there's nothing else for us to do here, you can just close the ticket.

**Comment by yyoncho** [comment]
@dennismayr afaik the performance issue was fixed, see https://github.com/emacs-lsp/lsp-mode/issues/851 . Before we continue investigating this issue, please make sure that you are using the latest dart-sdk (dart-sdk containing the fixes discussed in #851)

**Comment by dennismayr** [comment]
@yyoncho Will do; I'll report back during the day (gotta build a Flutter project for a tech interview, a good opportunity to test related issues).

**Comment by dennismayr** [comment]
@yyoncho I'm currently using `dart` _stable_ `2.4.0`.
(not a fan of bleeding edge stuff)

**Comment by yyoncho** [comment]
Looks like you are using fairly recent dart sdk. Can you attach the corresponding logs for the error? Also, make sure that you are running with lsp-print-io set to nil when testing the completion performance because the logging is very slow. Also, you may set lsp-print-performance and then inspect the \*lsp-log\* to check where the time goes. 

> ```emacs-lisp
> Emacs 26.2 (x86_64-pc-linux-gnu) of 2019-04-12 on lgw01-amd64-060
> Company 0.9.10
> 
> company-backends: (company-lsp php-extras-company company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-files
>              (company-dabbrev-code company-gtags company-etags company-keywords)
>              company-oddmuse company-dabbrev)
> 
> Used backend: company-lsp
> Major mode: dart-mode
> Prefix: (#("Build" 0 5
>    (fontified t face font-lock-type-face))
>  . t)
> 
> Completions: none(error fetching)
> ```

Are you sure that this company-diag is from the same thing that you have here: https://camo.githubusercontent.com/47bc1efed950943df2ac2abbe418d9002a1d10b1/68747470733a2f2f696d6775722e636f6d2f49543373437a562e706e67 . The list shows only one item.

**Comment by dennismayr** [comment]
Sorry about the delay.

Because of the project's nature, I had to downgrade the Dart SDK to version _2.3.0_ (stable), because we'll be using Flutter _1.5.4_ (stable) to avoid breaking things.

Now, for the following snippet
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());
class MyApp extends StatelessWidget{
  @override
  Widget build (BuildContext context) {

  }
}
```

the `lsp-print-io` data is the following:
[lsp-print-io log, compressed](https://drive.google.com/open?id=1qnlU4HR-SQ-gWtWAci1VhsGjXl67KFHl)

The `M-x company-diag` data is
```elisp
Emacs 26.2 (x86_64-pc-linux-gnu) of 2019-04-12 on lgw01-amd64-060
Company 0.9.10

company-backends: (company-lsp php-extras-company company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-files
             (company-dabbrev-code company-gtags company-etags company-keywords)
             company-oddmuse company-dabbrev)

Used backend: company-lsp
Major mode: dart-mode
Prefix: (#("BuildConte" 0 10
   (fontified t face font-lock-type-face))
 . t)

Completions: none(error fetching)
```

(I hope I got things right)

As of `lsp-print-performance`, I can't seem to find it; is it a toggleable option in the dotfile? `M-x` doesn't show anything alike in  `helm`

Regarding autocompletion: it looks as if the mode seemed unaware of imported elements in Dart that in other languages + `lsp`-modes are immediately suggested; e.g. imported GUI component classes have standardized names and structure, yet they're never autocompleted. Basically, it's almost like typing without autocomplete, only that autocompletion jumps at unnecessary times automatically.

I'll try to clarify the issue through the following example:

```dart
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('{_DM}; Startup Name Generator'),
      )
   );
}
```
This snippet is a part of the code that creates the top title bar of an app.

`Widget`, `BuildContext`, `return`, `Scaffold`, `appBar`, these are the bread & butter of Flutter workflow when coding a Dart-based app. However, they're never autocompleted.

However, once `appBar: AppBar (` has been typed, `title: ,` does get suggested. Most of the time, typing something like `appBar: AppBar (` and tapping Enter after the opening parenthesis automatically fills in the 1st autocomplete suggestion (an annoyance), having to manually delete it.

It's as if the standard, prerequisite classes were never autocompleted, but once filled in, all possible dependencies do get suggested.

(Phew, this grew long. Let me know what else I can help with)

**Comment by dennismayr** [comment]
Another case of autocompletion inconsistencies:

Something as common as `TextAlign` is never suggested as if it weren't recognized, but `TextAlign.center` is immediately suggested.
![Imgur](https://imgur.com/OpTCCmA.png)
![Imgur](https://imgur.com/21HlLon.png)

Entering `Widget` gets me an unwanted snippet, but there may be other culprits, I suppose, as I'm using _Spacemacs_ with `yasnippet`.
![Imgur](https://imgur.com/QwRoPEC.png)
![Imgur](https://imgur.com/rvPVOAI.png)

**Comment by itome** [comment]
@dennismayr dart language server try to auto complete non imported types, so when typing widgets, lsp-mode recieves massive amount of json response. Parsing this response takes so long time that you can't get auto complete results.
The response size shrunk in current beta mode. Can you try that one? 

To use nightly build sdk alongside with flutter,
1, Download nightly build from here https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/
2, unzip the sdk
3, Add following code in your `dotspacemacs/user-config`
```
```

**Comment by dennismayr** [comment]
Thanks for the prompt reply @itome! It's clearer for me now; I didn't really know how it works.

I'll download the nightly build tonight and share the results within the next couple of days.

**Comment by dennismayr** [comment]
I took a long-ish pause, since we're watching the total eclipse in Chile (92% visible here!), and tested the _nightly_ build.

Typing `Wid` to autocomplete as `Widget` took about 4 initial seconds of latency, since my laptop is a 2010 ThinkPad T410s i5 with a sluggish sub-5400rpm hard drive, but lo and behold!

![Imgur](https://imgur.com/P0yjGmn.png)

There's definitely some work being done on the right track in the _SDK_; not an `lsp` problem, so @yyoncho  will have one less thing to worry about.

**Comment by dennismayr** [comment]
There are still some minor quirks to iron out (such as getting `prefix0` automatically inserted when autocompleting `BuildContext`), but it's all in all more usable now.

![Imgur](https://imgur.com/JgflQqG.png)

![Imgur](https://imgur.com/8VLlwcC)

![Imgur](https://imgur.com/L5rTAFg)

![Imgur](https://imgur.com/I0557Op)

**Comment by dennismayr** [comment]
There's also the cursor going back to line 1 whenever you correctly complete a block of code and close it with a colon `;`.

**Comment by yyoncho** [comment]
@dennismayr thanks, I will take a look. Can you post a sample project(I have zero dart experience) and the steps to build import stuff for that project if any and the steps to reproduce each of the issues because I lost track what works and what does not work? I assume that you are using spacemacs if this is so you may paste your configuration.

**Comment by dennismayr** [comment]
Sure thing!

A basic Flutter app written in Dart looks like this:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

It's a bit like a Node app written in some form of TypeScript.
This will create a very simple _"Hello World"_ app.

Just in case they're needed, here's the [Flutter.dev](https://flutter.dev/docs/get-started/install) framework install instructions.

[My Spacemacs dotfile](https://pastebin.com/aG6yeYq7)

@itome's _nightly_ Dart SDK build did help in getting autocompletion to work, as it seems to provide `lsp` with smaller chunks of data; I've put it in `~/dart-sdk` and added `(dart :variables dart-sdk-path "~/dart-sdk/")` as layer variable to use `nightly` instead of the Flutter SDK's provided Dart version (2.3.0 in `stable`, 2.4.0 in `beta`).

Let me know what else I can provide you with.

**Comment by yyoncho** [comment]
@dennismayr From what I can see the server is returning prefix0.BuildContext (cc @DanTup).



```
[Trace - 08:58:15 AM] Received response 'completionItem/resolve - (3008)' in 31ms.
Result: {
  "data": {
    "rLength": 3,
    "rOffset": 190,
    "displayUri": "package:flutter/material.dart",
    "libId": 265,
    "offset": 193,
    "file": "/home/kyoncho/Sources/my_project_name/lib/main.dart"
  },
  "additionalTextEdits": [],
  "textEdit": {
    "newText": "prefix0.BuildContext",
    "range": {
      "end": {
        "character": 18,
        "line": 7
      },
      "start": {
        "character": 15,
        "line": 7
      }
    }
  },
  "insertText": "prefix0.BuildContext",
  "sortText": "999993",
  "documentation": {
    "value": "A handle to the location of a widget in the widget tree.\n\nThis class presents a set of methods that can be used from\n[StatelessWidget.build] methods and from methods on [State] objects.\n\n[BuildContext] objects are passed to [WidgetBuilder] functions (such as\n[StatelessWidget.build]), and are available from the [State.context] member.\nSome static functions (e.g. [showDialog], [Theme.of], and so forth) also\ntake build contexts so that they can act on behalf of the calling widget, or\nobtain data specifically for the given context.\n\nEach widget has its own [BuildContext], which becomes the parent of the\nwidget returned by the [StatelessWidget.build] or [State.build] function.\n(And similarly, the parent of any children for [RenderObjectWidget]s.)\n\nIn particular, this means that within a build method, the build context of\nthe widget of the build method is not the same as the build context of the\nwidgets returned by that build method. This can lead to some tricky cases.\nFor example, [Theme.of(context)] looks for the nearest enclosing [Theme] of\nthe given build context. If a build method for a widget Q includes a [Theme]\nwithin its returned widget tree, and attempts to use [Theme.of] passing its\nown context, the build method for Q will not find that [Theme] object. It\nwill instead find whatever [Theme] was an ancestor to the widget Q. If the\nbuild context for a subpart of the returned tree is needed, a [Builder]\nwidget can be used: the build context passed to the [Builder.builder]\ncallback will be that of the [Builder] itself.\n\nFor example, in the following snippet, the [ScaffoldState.showSnackBar]\nmethod is called on the [Scaffold] widget that the build method itself\ncreates. If a [Builder] had not been used, and instead the `context`\nargument of the build method itself had been used, no [Scaffold] would have\nbeen found, and the [Scaffold.of] function would have returned null.\n\n```dart\n  @override\n  Widget build(BuildContext context) {\n    // here, Scaffold.of(context) returns null\n    return Scaffold(\n      appBar: AppBar(title: Text('Demo')),\n      body: Builder(\n        builder: (BuildContext context) {\n          return FlatButton(\n            child: Text('BUTTON'),\n            onPressed: () {\n              // here, Scaffold.of(context) returns the locally created Scaffold\n              Scaffold.of(context).showSnackBar(SnackBar(\n                content: Text('Hello.')\n              ));\n            }\n          );\n        }\n      )\n    );\n  }\n```\n\nThe [BuildContext] for a particular widget can change location over time as\nthe widget is moved around the tree. Because of this, values returned from\nthe methods on this class should not be cached beyond the execution of a\nsingle synchronous function.\n\n[BuildContext] objects are actually [Element] objects. The [BuildContext]\ninterface is used to discourage direct manipulation of [Element] objects.",
    "kind": "markdown"
  },
  "kind": 7,
  "label": "BuildContext"
}
```

Can you provide steps to reproduce for that (or gif)?

> There's also the cursor going back to line 1 whenever you correctly complete a block of code and close it with a colon ;. One has to keep track of the line of code one was working on, because it will be necessary to scroll back down.

**Comment by DanTup** [comment]
There was a bug in the Dart SDK that would return a prefix where it wasn't neceesary, but that should be fixed. It will still return prefixes where necessary to avoid naming conflicts. The JSON has also been significantly reduced (by removing docs and some other fields until the resolve step) that should improve performance.

The current stable version of Flutter (v1.5.4-hotfix.2) does not have many of these fixes, so if you're doing Flutter you would be best switching to the beta channel (v1.7.8+hotfix.2) to avoid the issues until the stable channel next updates.

If the JSON for completion is still causing problems, you can set `suggestFromUnimportedLibraries: false` in initializationOptions to prevent unimported items being included ([see here](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md#initialization-options)).

If this doesn't address all of the issues above (which are believed to be SDK-related), let me know more specifics and I can take a look. Thanks!

**Comment by dennismayr** [comment]
@dantup Thanks for the clarification! I've spoken to my team about using the _beta_ channel; since there are no breaking changes, it's OK with them, I've just switched to `1.7.8+hotfix.2` to keep on testing.

@yyoncho On the code snippet I've provided, if you have _Flutter_ installed, after importing `import 'package:flutter/material.dart';`, when you reach line 17...

```dart
         ),
         body: Center(
           child: Text('Hello World'),
         ),
       ),
     );  // <= line 17, this semicolon

```
...entering the semicolon to close the whole `Widget build(BuildContext context)...` widget brings the cursor back to line 1 character 1. This happens with almost every semicolon entered to close an expression.

I haven't tried it without the _Flutter_ SDK, as this framework is the reason I've begun using Dart. I will try on monday, as I have to turn up a project today to get a Flutter job and my hands are full and shaking :laughing:  (wish me luck)

**Comment by yyoncho** [comment]
> @yyoncho On the code snippet I've provided, if you have Flutter installed, after importing import 'package:flutter/material.dart';, when you reach line 17...

I believe this is caused by on type formatting bug which I am currently working on. Can you confirm that the issue disappears after setting lsp-enable-on-type-formatting to nil?

**Comment by dennismayr** [comment]
I just tried it.

Cursor return issue disappears with `(lsp-enable-on-type-formatting nil)`.

**Comment by dennismayr** [comment]
@DanTup I've upgraded to SDK version 1.7.8 beta, ran `flutter pub upgrade` on my projects, but the `(prefix.0.BuildContext)` bug still comes up every now and then.

Example:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

void main() => runApp(const myApp());

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Example Title',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Example Title'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key, @required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: ListView(
          children: _buildProductList(context),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: new Icon(Icons.add),
        onPressed: _addProductToCart,
      ),
    );
  }

  List<Widget> _buildProductList(prefix0.BuildContext) // <=== _buildProductList(BuildContext context)

}
```

It pops up a lot less frequently, but it's apparently still there.

@yyoncho The cursor issue is definitely gone.

**Comment by yyoncho** [comment]
@dennismayr I have fixed the issue with on type formatting for emacs 26+. Unfortunately, it is not possible to make it work for older emacs since it does not have the required functions. The issue with prefix0(if it is still present) is not on emacs side.

**Comment by DanTup** [comment]
@dennismayr I don't seem to be able to repro with your code sample through VS Code (either on `beta` or `master` branches), though it's not using in LSP (though in theory that shouldn't affect this). I'll see if I can repro through the LSP server when back at my main machine tomorrow. In the meantime if you can easily capture a log (by running the server with `--instrumentation-log-file /some/log/file`) and raise an issue at https://github.com/dart-lang/sdk and mention me on it, that might help me track it down.

Thanks!

**Comment by dennismayr** [comment]
@yyoncho No worries, I'm using Emacs 26+, it's better performing.

@DanTup Will do!

Thanks to both of you for the time and effort. Everything is running better than before; you've made a better Dart+Flutter experience on Emacs.

**Comment by DanTup** [comment]
I tested again via the LSP server today and using current Flutter `beta` branch, but still can't repro the `prefix0` issue:

![Screenshot 2019-07-08 at 3 59 22 pm](https://user-images.githubusercontent.com/1078012/60820482-6e0e2600-a199-11e9-8139-a37a9bdd386a.png)

Whichever one I pick, it only inserts `BuildContext`. Before opening an issue - just check that you're on the latest version - I think you need to do both `flutter channel beta` and `flutter upgrade` to get latest. If you're on the latest version (1.7.8+hotfix.2) then please do open an issue in dart-lang/sdk with a log and CC me. Thanks!

**Comment by dennismayr** [comment]
@DanTup I'll keep on testing 1.7.8 beta; I'll let you know if the problem comes up again.
Thanks!

**Comment by dennismayr** [comment]
Problem solved with upgrade to the new stable SDK (`1.9.1+hotfix.2`).
Also, language server performance is much better.

Cheers!

**Comment by itome** [comment]
@dennismayr 
I made PR that make it possible to pass initialization options to dart_analysis_server. Set `suggestFromUnimportedLibraries` to `nil` may improve performance in exchange of unimported library completion disabled.

https://github.com/emacs-lsp/lsp-mode/pull/1197
